cc_binary(
    name = "RAM_test",
    srcs = [
        "RAM.cc",
        "RAM.h",
        "test_RAM.cc",
    ],
    deps = [
        "//main/register:register_lib",
    ],
)

# cc_library(
#     name = "RAM_lib",
#     srcs = [
#         "RAM.cc",
#         "RAM.h",
#     ],
#     deps = [
#         "//main/register:register_lib",
#     ],
# )
